### ISSUE TITLE
helm_release.istio-remote-eks fails on first run

### ISSUE THREAD

**Issue by magic7s** [magic7s/k8s-hybrid-cloud#3]
`helm_release.istio-remote-eks: error installing: Post http://localhost/apis/extensions/v1beta1/namespaces/kube-system/deployments: dial tcp [::1]:80: connect: connection refused`

helm tries to install before KUBECONFIG file is available and tries to use default connection url.

**Comment by magic7s** [comment]
Work around: run `terraform apply` again to finish the tasks. The KUBECONFIG file should be present now.

**Comment by rosscdh** [comment]
Could you not use `depends_on = ["localfile_kube_conf"]` and https://www.terraform.io/docs/providers/local/d/file.html or `null_resource ` to set the state requirement?

**Comment by magic7s** [comment]
The file creation is done within the eks module. I am not sure how to reference it directly. I am already using `depends_on = ["module.eks"]`

If I try `depends_on = ["local_file.kubeconfig"]` or `depends_on = "module.eks.local_file.kubeconfig"` I get an error.

```
Error: helm_release.istio-remote-eks: resource depends on non-existent resource 'local_file.kubeconfig'
Error: helm_release.istio-remote-eks: resource depends on non-existent module 'eks.local_file.kubeconfig'
```
